-- identity-columns.sql: Test GENERATED AS IDENTITY columns.
-- Oracle 12c+ supports identity columns. Verifies OLR captures the
-- auto-generated values correctly.

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET ECHO OFF

-- Setup: drop and recreate tables
DECLARE
    v_table_exists NUMBER;
BEGIN
    FOR t IN (SELECT table_name FROM user_tables
              WHERE table_name IN ('TEST_IDENTITY_ALWAYS', 'TEST_IDENTITY_DEFAULT')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' PURGE';
    END LOOP;
END;
/

-- GENERATED ALWAYS: cannot specify value in INSERT
CREATE TABLE TEST_IDENTITY_ALWAYS (
    id     NUMBER GENERATED ALWAYS AS IDENTITY,
    name   VARCHAR2(100),
    value  NUMBER,
    CONSTRAINT pk_identity_always PRIMARY KEY (id)
);

-- GENERATED BY DEFAULT: can optionally specify value
CREATE TABLE TEST_IDENTITY_DEFAULT (
    id     NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 10),
    name   VARCHAR2(100),
    value  NUMBER,
    CONSTRAINT pk_identity_default PRIMARY KEY (id)
);

ALTER TABLE TEST_IDENTITY_ALWAYS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE TEST_IDENTITY_DEFAULT ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Record start SCN
DECLARE
    v_start_scn NUMBER;
BEGIN
    SELECT current_scn INTO v_start_scn FROM v$database;
    DBMS_OUTPUT.PUT_LINE('FIXTURE_SCN_START: ' || v_start_scn);
END;
/

-- DML: INSERT into ALWAYS identity (id auto-assigned: 1, 2, 3)
INSERT INTO TEST_IDENTITY_ALWAYS (name, value) VALUES ('Alice', 100);
INSERT INTO TEST_IDENTITY_ALWAYS (name, value) VALUES ('Bob', 200);
INSERT INTO TEST_IDENTITY_ALWAYS (name, value) VALUES ('Charlie', 300);
COMMIT;

-- DML: INSERT into BY DEFAULT identity (auto: 100, 110)
INSERT INTO TEST_IDENTITY_DEFAULT (name, value) VALUES ('auto-1', 10);
INSERT INTO TEST_IDENTITY_DEFAULT (name, value) VALUES ('auto-2', 20);
COMMIT;

-- DML: INSERT into BY DEFAULT with explicit id
INSERT INTO TEST_IDENTITY_DEFAULT (id, name, value) VALUES (999, 'explicit', 30);
COMMIT;

-- DML: UPDATE rows in both tables
UPDATE TEST_IDENTITY_ALWAYS SET name = 'Alice Updated', value = 150 WHERE id = 1;
UPDATE TEST_IDENTITY_DEFAULT SET name = 'auto-1 updated' WHERE id = 100;
COMMIT;

-- DML: DELETE from both tables
DELETE FROM TEST_IDENTITY_ALWAYS WHERE id = 2;
DELETE FROM TEST_IDENTITY_DEFAULT WHERE id = 999;
COMMIT;

-- Record end SCN
DECLARE
    v_end_scn NUMBER;
BEGIN
    SELECT current_scn INTO v_end_scn FROM v$database;
    DBMS_OUTPUT.PUT_LINE('FIXTURE_SCN_END: ' || v_end_scn);
END;
/

EXIT
