-- rac-alternating-commits.rac.sql: Rapid single-row commits from alternating nodes.
-- @TAG rac
-- Tests the SCN watermark and round-robin parsing with many small transactions
-- from alternating nodes. Exercises the per-thread context switching on every cycle.

-- @SETUP
DECLARE
    v_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_exists
    FROM user_tables WHERE table_name = 'TEST_RAC_ALTERNATING';
    IF v_table_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE TEST_RAC_ALTERNATING PURGE';
    END IF;
END;
/

CREATE TABLE TEST_RAC_ALTERNATING (
    id     NUMBER PRIMARY KEY,
    source VARCHAR2(10),
    val    NUMBER
);

ALTER TABLE TEST_RAC_ALTERNATING ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

DECLARE
    v_start_scn NUMBER;
BEGIN
    SELECT current_scn INTO v_start_scn FROM v$database;
    DBMS_OUTPUT.PUT_LINE('FIXTURE_SCN_START: ' || v_start_scn);
END;
/

-- 20 alternating single-row commits

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (1, 'N1', 1);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (2, 'N2', 2);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (3, 'N1', 3);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (4, 'N2', 4);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (5, 'N1', 5);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (6, 'N2', 6);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (7, 'N1', 7);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (8, 'N2', 8);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (9, 'N1', 9);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (10, 'N2', 10);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (11, 'N1', 11);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (12, 'N2', 12);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (13, 'N1', 13);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (14, 'N2', 14);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (15, 'N1', 15);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (16, 'N2', 16);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (17, 'N1', 17);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (18, 'N2', 18);
COMMIT;

-- @NODE1
INSERT INTO TEST_RAC_ALTERNATING VALUES (19, 'N1', 19);
COMMIT;

-- @NODE2
INSERT INTO TEST_RAC_ALTERNATING VALUES (20, 'N2', 20);
COMMIT;

-- Mix in some updates on the other node's rows

-- @NODE1
UPDATE TEST_RAC_ALTERNATING SET val = val + 100 WHERE id = 2;
COMMIT;

-- @NODE2
UPDATE TEST_RAC_ALTERNATING SET val = val + 100 WHERE id = 1;
COMMIT;

-- @NODE1
DELETE FROM TEST_RAC_ALTERNATING WHERE id = 20;
COMMIT;

-- @NODE2
DELETE FROM TEST_RAC_ALTERNATING WHERE id = 19;
COMMIT;
