-- subquery-dml.sql: Test DML with subqueries.
-- Run as PDB user (e.g., olr_test/olr_test@//localhost:1521/FREEPDB1)
--
-- Verifies that OLR correctly captures DML generated by UPDATE with subquery,
-- DELETE with correlated subquery, and INSERT..SELECT patterns.
-- These all generate standard redo records but exercise different SQL paths.
--
-- Outputs: FIXTURE_SCN_START: <scn> and FIXTURE_SCN_END: <scn>

SET SERVEROUTPUT ON
SET FEEDBACK OFF
SET ECHO OFF

-- Setup: drop and recreate tables
DECLARE
    v_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_exists
    FROM user_tables WHERE table_name = 'TEST_SUBQ_MAIN';
    IF v_table_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE TEST_SUBQ_MAIN PURGE';
    END IF;

    SELECT COUNT(*) INTO v_table_exists
    FROM user_tables WHERE table_name = 'TEST_SUBQ_REF';
    IF v_table_exists > 0 THEN
        EXECUTE IMMEDIATE 'DROP TABLE TEST_SUBQ_REF PURGE';
    END IF;
END;
/

CREATE TABLE TEST_SUBQ_MAIN (
    id     NUMBER PRIMARY KEY,
    name   VARCHAR2(100),
    val    NUMBER,
    status VARCHAR2(20)
);

CREATE TABLE TEST_SUBQ_REF (
    id     NUMBER PRIMARY KEY,
    ref_id NUMBER,
    label  VARCHAR2(100)
);

ALTER TABLE TEST_SUBQ_MAIN ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE TEST_SUBQ_REF ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Record start SCN
DECLARE
    v_start_scn NUMBER;
BEGIN
    SELECT current_scn INTO v_start_scn FROM v$database;
    DBMS_OUTPUT.PUT_LINE('FIXTURE_SCN_START: ' || v_start_scn);
END;
/

-- Seed data
INSERT INTO TEST_SUBQ_MAIN VALUES (1, 'Alice', 100, 'active');
INSERT INTO TEST_SUBQ_MAIN VALUES (2, 'Bob', 200, 'active');
INSERT INTO TEST_SUBQ_MAIN VALUES (3, 'Charlie', 300, 'active');
INSERT INTO TEST_SUBQ_MAIN VALUES (4, 'Diana', 400, 'active');
COMMIT;

INSERT INTO TEST_SUBQ_REF VALUES (1, 1, 'ref-alice');
INSERT INTO TEST_SUBQ_REF VALUES (2, 2, 'ref-bob');
INSERT INTO TEST_SUBQ_REF VALUES (3, 3, 'ref-charlie');
COMMIT;

-- UPDATE with scalar subquery
UPDATE TEST_SUBQ_MAIN m SET
    m.val = (SELECT COUNT(*) * 1000 FROM TEST_SUBQ_REF r WHERE r.ref_id = m.id)
WHERE m.id <= 3;
COMMIT;

-- DELETE with correlated subquery (EXISTS)
DELETE FROM TEST_SUBQ_MAIN m
WHERE NOT EXISTS (SELECT 1 FROM TEST_SUBQ_REF r WHERE r.ref_id = m.id);
COMMIT;

-- UPDATE with IN subquery
UPDATE TEST_SUBQ_MAIN SET status = 'has-ref'
WHERE id IN (SELECT ref_id FROM TEST_SUBQ_REF);
COMMIT;

-- Record end SCN
DECLARE
    v_end_scn NUMBER;
BEGIN
    SELECT current_scn INTO v_end_scn FROM v$database;
    DBMS_OUTPUT.PUT_LINE('FIXTURE_SCN_END: ' || v_end_scn);
END;
/

EXIT
